# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Easy-All 2.0' do
  pod 'Masonry',  '1.1.0'
  pod 'MJExtension', '3.0.13'
  pod 'SDWebImage', '4.3.3'
  pod 'HLFUIImageExtension', '0.1.1'
  pod 'CocoaLumberjack', '3.4.1'
end
